-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- Users Table (Custom Auth as per requirement 'ID is student name')
create table if not exists users (
  username text primary key,
  password text not null, -- Storing directly for simplicity as per request, but ideally should be hashed
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Problems Table
create table if not exists problems (
  id bigint generated by default as identity primary key,
  domain text,
  body text not null, -- Markdown/Latex content
  source text,
  answer text not null, -- Max 3 chars, integer
  score integer default 0,
  solution text, -- Explanation
  image1 text, -- Problem image URL
  image2 text, -- Solution image URL
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Solve History (For Osolnote/Wrong Answer Note)
create table if not exists solve_history (
  id uuid default uuid_generate_v4() primary key,
  user_id text references users(username) on delete cascade not null,
  problem_id bigint references problems(id) on delete cascade not null,
  user_answer text,
  is_correct boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS Policies (Optional but recommended, keeping open for now for simplicity)
alter table users enable row level security;
alter table problems enable row level security;
alter table solve_history enable row level security;

-- Open access policies for development (WARNING: Secure this for production)
create policy "Allow public read/write access to users" on users for all using (true) with check (true);
create policy "Allow public read/write access to problems" on problems for all using (true) with check (true);
create policy "Allow public read/write access to solve_history" on solve_history for all using (true) with check (true);

-- Bookmarks table for "Review" tag
create table review_bookmarks (
  id bigint generated by default as identity primary key,
  user_id text not null,
  problem_id bigint references problems(id) not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, problem_id)
);

-- Policy for bookmarks (public access for simplicity, or user constrained)
create policy "Enable read access for all users" on review_bookmarks for select using (true);
create policy "Enable insert for all users" on review_bookmarks for insert with check (true);
create policy "Enable delete for all users" on review_bookmarks for delete using (true);
